version: '2'
services:
  db:
    image: postgres:9.4
  web:
    build: .
    command: "bash /wheel/entrypoint.sh"
    volumes:
      - .:/wheel
    ports:
      - "9000:9000"
    depends_on:
      - db
